name: pressbooks-local
recipe: wordpress
config:
  webroot: web
  via: nginx
  xdebug: true
  config:
    php: config_services/php.ini
    database: config_services/my.cnf
    vhosts: config_services/nginx.conf
proxy:
  appserver_nginx:
    - pressbooks.test
env_file:
  - config_services/.env
services:
  database:
    type: mariadb:10.5.23
    portforward: 32777
  redis:
    type: redis:5.0
    portforward: 6379
  node:
    type: node
  appserver:
    type: php:8.1
    xdebug: true
    environment:
      PHP_IDE_CONFIG: "serverName=appserver"
      XDEBUG_SESSION_START: lando
    build_as_root:
      - scripts/pressbooks_required_libraries.sh
    build:
      - composer install
  mailhog:
    hogfrom:
      - appserver
    type: mailhog
    overrides:
      image: anatomicjc/mailhog:1.0.1
    portforward: 8025
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  npm:
    service: node
  node:
    service: node
  install-tests:
    description: Install test requirements
    cmd:
      - appserver: scripts/prepare_tests_environment.sh
  test:
    description: Run all Unit Tests
    cmd:
      - appserver: composer run test
  install-acceptance-tests:
    description: Install acceptance test requirements
    cmd:
      - appserver: scripts/prepare_acceptance_tests_environment.sh
  testbygroup:
    description: Run tests within a group
    cmd:
      - appserver: composer run group_test
  testbyfilter:
    description: Run tests by filter
    cmd:
      - appserver: composer run filter_test
